runtime: python27
api_version: 1
threadsafe: true
skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?.*/RCS/.*$
 - ^(.*/)?\..*$
 - USNationalsApp/
 - external/groupifier-next
 - external/icons
 - scripts/
builtins:
 - deferred: on

libraries:
 - name: webapp2
   version: latest

handlers:
 - url: /admin/.*
   script: usnationals.app
   secure: always
   login: admin
 - url: /static
   static_dir: src/static
 - url: /.*
   script: usnationals.app
   secure: always
